### ISSUE TITLE
Regression regarding `resolveOnMainThread `

### ISSUE THREAD

**Issue by alladinian** [s4cha/ws#42] opened 2017-05-25 08:48 UTC
Obviously, this is not a bug per se, but it is worth noting that v2.0.3 breaks a lot of existing code by deallocating prematurely when the first promise is not retained manually (for example in nested functions)... Something like: 

``` swift
func fetchData() {
	
	showLoading()
	
	func fetch() -> Promise<Something> {
		...
	}
	
	fetch().resolveOnMainThread()
	.then { data in
		...
	}
	.onError { error in
		...
	}
	.finally { [weak self] in
		self?.hideLoading()
	}
	
}
```

**Comment by s4cha** [comment] 2017-05-28 08:33
@alladinian Thanks a lot for reporting this.
Indeed latest version uses latest `then` version that has been patched for some retain cycles.
Looks like the patch ends up changing the behaviour down the road...
I'll try to look at this this week and keep you posted :)

**Comment by s4cha** [comment] 2017-08-12 13:07
@alladinian I haven't forgotten you :)

I've been working on an update for then (https://github.com/freshOS/then/pull/29)
I'm curious if that would solve your issue and the regressions you pointed out.

Could you elaborate a bit more so that we can test it out ?

Have a wonderful weekend,

**Comment by alladinian** [comment] 2017-08-13 11:38
@s4cha Hi there!
No worries, I appreciate it :)
You're right, I should have elaborated more on this.

The problem I stumbled upon was related to `resolveOnMainThread()` so I don't think this is an issue of `then` library. 

The [implementation of the function](https://github.com/freshOS/ws/blob/54055879bfe55496fb7dc06219f92ee9f68b5317/ws/WS.swift#L155) captures `self` (an instance of a `Promise`) as `weak`, which means that if we do _not_ hold a `strong` reference to the promise on which we chained a `resolveOnMainThread()`, we break the whole chain (since the first promise is deallocated when we reach the end of the local scope - see my example above. Just fill the blanks with print statements & you should be able to verify that `finally/hideLoading()` is never called...). 

The problem is solved by not specifying the captured `self` as `weak`, but I did not verify that it doesn't introduce any memory leaks... 

I hope that this makes sense and it's helpful to you,

Thanks again for this great project,

Vasilis

**Comment by maxkonovalov** [comment] 2017-08-21 21:39
Hey guys, I can confirm that `resolveOnMainThread()` stopped working for me, too. The resulting `then`, `onError`, etc. never get called. I tried to keep a strong ref to the returned Promise, but it didn't help either.

**Comment by s4cha** [comment] 2017-09-25 12:10
Hi @alladinian @maxkonovalov ,
This should be solved in 3.0.0 (Swift 4) 🎉
Thanks a ton!

**Comment by s4cha** [comment] 2018-01-03 10:14
@alladinian can we close this issue?

**Comment by alladinian** [comment] 2018-01-03 10:38
@s4cha Sure, seems to be fixed. Also... Happy new year guys  🍻

**Closed as completed** 2018-01-03 10:38 UTC

**Comment by s4cha** [comment] 2018-01-03 10:42
Yeah! You to @alladinian thanks again for your time and effort !!! 
Let 2018 be awesome!!!! 🍾
